#
# build-and-test.yml: GitHub Action for building and testing
#
# SPDX-License-Identifier: BSD-3-Clause
#
# This file is part of Sweet B, a safe, compact, embeddable library for
# elliptic curve cryptography.
#
# https://github.com/westerndigitalcorporation/sweet-b
#
# Copyright (c) 2022 Western Digital Corporation or its affiliates.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:

    # Don't run duplicate `push` jobs for PRs within the same repository.
    # Solution from https://github.com/briansmith/ring/blob/0f3bf0031a8dbba741b26f1f02ebde6b7db4a3d6/.github/workflows/ci.yml#L9-L10
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    name: "Build and Test"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        configuration: [Debug, Release]
        processor: [default, arm, timecop]
        include:
          - processor: default
            toolchain-option: "-DCMAKE_C_COMPILER=clang"
          - processor: arm
            toolchain-option: "-DCMAKE_TOOLCHAIN_FILE=arm.cmake"
            run-wrap: qemu-arm
            packages: gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user
          - processor: timecop
            toolchain-option: "-DSB_TIME=1 -DSB_TEST_VERIFY_QR=0"
            run-wrap: valgrind --error-exitcode=255
            packages: valgrind

    steps:
    - uses: actions/checkout@v3

    - name: system-packages
      if: ${{ matrix.packages != '' }}
      run: sudo apt install -y ${{ matrix.packages }}

    - name: build
      run: |
        cmake -Bcmake-build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ${{ matrix.toolchain-option }} -DSB_TEST=1
        make -Ccmake-build VERBOSE=1
    
    - name: test
      run: ${{matrix.run-wrap}} ./cmake-build/sb_test